services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./sources:$PHP_USER_HOME_DIRECTORY
    ports:
      - $SERVER_PORT:80

  php:
    container_name: php
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./sources:$PHP_USER_HOME_DIRECTORY
  migration:
    container_name: migration
    restart: unless-stopped
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./db:$PHP_USER_HOME_DIRECTORY
    command: sh -c "php /home/php/migrations/0001_initial.php && php /home/php/migrations/0002_add_photos_table.php && php /home/php/migrations/0003_add_password_reset_table.php"

  mariadb:
    container_name: mariadb
    restart: unless-stopped
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    user: root
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
